name: p2p_app
description: P2P services marketplace MVP (Flutter + Supabase)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  supabase_flutter: ^2.12.0
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

