-- P2P Services MVP schema for Supabase (Postgres)
-- Apply in Supabase SQL editor or via Supabase CLI migrations.
--
-- Notes:
-- - This script expects Supabase (auth schema exists).
-- - After applying, set your admin by updating profiles.is_admin = true for your user id.
-- - Create Storage buckets: 'avatars' and 'ads' (public or private as desired).

begin;

-- Extensions (Supabase typically enables these, but keep safe)
create extension if not exists pgcrypto;

-- Enums
do $$
begin
  if not exists (select 1 from pg_type where typname = 'provider_request_status') then
    create type public.provider_request_status as enum ('pending', 'approved', 'rejected');
  end if;

  if not exists (select 1 from pg_type where typname = 'ad_type') then
    create type public.ad_type as enum ('banner', 'interstitial');
  end if;

  if not exists (select 1 from pg_type where typname = 'job_status') then
    create type public.job_status as enum ('open', 'in_progress', 'completed', 'cancelled');
  end if;
end$$;

-- Utility: updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- profiles (mirrors auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  is_provider boolean not null default false,
  is_customer boolean not null default true,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

-- auto-create profile when a new auth.user is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- provider details (1:1)
create table if not exists public.provider_details (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  headline text,
  bio text,
  years_experience int,
  average_rating numeric(3,2) not null default 0,
  jobs_completed int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_provider_details_set_updated_at on public.provider_details;
create trigger trg_provider_details_set_updated_at
before update on public.provider_details
for each row execute procedure public.set_updated_at();

-- service categories
create table if not exists public.service_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon_key text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_service_categories_set_updated_at on public.service_categories;
create trigger trg_service_categories_set_updated_at
before update on public.service_categories
for each row execute procedure public.set_updated_at();

-- provider services (many-to-many)
create table if not exists public.provider_services (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint not null references public.service_categories(id) on delete restrict,
  service_radius_km int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, category_id)
);

drop trigger if exists trg_provider_services_set_updated_at on public.provider_services;
create trigger trg_provider_services_set_updated_at
before update on public.provider_services
for each row execute procedure public.set_updated_at();

-- locations (simple MVP; 0..n locations per profile)
create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  city text,
  region text,
  country text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_locations_set_updated_at on public.locations;
create trigger trg_locations_set_updated_at
before update on public.locations
for each row execute procedure public.set_updated_at();

-- provider role requests (admin approval)
create table if not exists public.provider_role_requests (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  status public.provider_request_status not null default 'pending',
  motivation text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null
);

create index if not exists idx_provider_role_requests_profile on public.provider_role_requests(profile_id);
create index if not exists idx_provider_role_requests_status on public.provider_role_requests(status);

-- ad clients (companies or provider advertisers)
create table if not exists public.ad_clients (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete set null,
  company_name text not null,
  contact_email text,
  contact_phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_ad_clients_set_updated_at on public.ad_clients;
create trigger trg_ad_clients_set_updated_at
before update on public.ad_clients
for each row execute procedure public.set_updated_at();

-- ads
create table if not exists public.ads (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.ad_clients(id) on delete cascade,
  type public.ad_type not null,
  image_url text not null,
  redirect_url text,
  target_category_id bigint references public.service_categories(id) on delete set null,
  is_active boolean not null default true,
  start_date date,
  end_date date,
  max_impressions bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_ads_set_updated_at on public.ads;
create trigger trg_ads_set_updated_at
before update on public.ads
for each row execute procedure public.set_updated_at();

create index if not exists idx_ads_active on public.ads(is_active);
create index if not exists idx_ads_target_category on public.ads(target_category_id);

-- ad impressions
create table if not exists public.ad_impressions (
  id uuid primary key default gen_random_uuid(),
  ad_id uuid not null references public.ads(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  shown_at timestamptz not null default now(),
  clicked boolean not null default false
);

create index if not exists idx_ad_impressions_ad on public.ad_impressions(ad_id);
create index if not exists idx_ad_impressions_profile on public.ad_impressions(profile_id);

-- jobs (optional; lightweight for MVP)
create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles(id) on delete cascade,
  provider_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.service_categories(id) on delete set null,
  title text not null,
  description text,
  city text,
  budget_min numeric(12,2),
  budget_max numeric(12,2),
  status public.job_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_jobs_set_updated_at on public.jobs;
create trigger trg_jobs_set_updated_at
before update on public.jobs
for each row execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------

-- Request provider role (user)
create or replace function public.request_provider_role(motivation text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := auth.uid();
  v_existing uuid;
  v_new_id uuid;
begin
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  -- prevent multiple pending requests
  select id into v_existing
  from public.provider_role_requests
  where profile_id = v_profile_id and status = 'pending'
  limit 1;

  if v_existing is not null then
    return v_existing;
  end if;

  insert into public.provider_role_requests(profile_id, status, motivation)
  values (v_profile_id, 'pending', motivation)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Approve/reject provider request (admin)
create or replace function public.resolve_provider_request(request_id uuid, approve boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := auth.uid();
  v_is_admin boolean;
  v_profile_id uuid;
begin
  if v_admin_id is null then
    raise exception 'Not authenticated';
  end if;

  select is_admin into v_is_admin from public.profiles where id = v_admin_id;
  if coalesce(v_is_admin, false) = false then
    raise exception 'Not authorized';
  end if;

  select profile_id into v_profile_id from public.provider_role_requests where id = request_id;
  if v_profile_id is null then
    raise exception 'Request not found';
  end if;

  update public.provider_role_requests
  set status = case when approve then 'approved' else 'rejected' end,
      resolved_at = now(),
      resolved_by = v_admin_id
  where id = request_id;

  if approve then
    update public.profiles set is_provider = true where id = v_profile_id;
    insert into public.provider_details(profile_id) values (v_profile_id)
    on conflict (profile_id) do nothing;
  end if;
end;
$$;

-- Record ad impression/click (authenticated)
create or replace function public.record_ad_impression(p_ad_id uuid, p_clicked boolean default false)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := auth.uid();
  v_new_id uuid;
begin
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  insert into public.ad_impressions(ad_id, profile_id, clicked)
  values (p_ad_id, v_profile_id, coalesce(p_clicked, false))
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- ---------------------------------------------------------------------
-- RLS policies
-- ---------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.provider_details enable row level security;
alter table public.service_categories enable row level security;
alter table public.provider_services enable row level security;
alter table public.locations enable row level security;
alter table public.provider_role_requests enable row level security;
alter table public.ad_clients enable row level security;
alter table public.ads enable row level security;
alter table public.ad_impressions enable row level security;
alter table public.jobs enable row level security;

-- profiles: everyone can read for directory; only owner can update
drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
on public.profiles for select
using (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- provider_details: read all; update/insert only own
drop policy if exists "provider_details_select_all" on public.provider_details;
create policy "provider_details_select_all"
on public.provider_details for select
using (true);

drop policy if exists "provider_details_write_own" on public.provider_details;
create policy "provider_details_write_own"
on public.provider_details for insert
with check (auth.uid() = profile_id);

drop policy if exists "provider_details_update_own" on public.provider_details;
create policy "provider_details_update_own"
on public.provider_details for update
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

-- service_categories: read all active; only admin writes
drop policy if exists "service_categories_select_active" on public.service_categories;
create policy "service_categories_select_active"
on public.service_categories for select
using (is_active = true);

drop policy if exists "service_categories_admin_write" on public.service_categories;
create policy "service_categories_admin_write"
on public.service_categories for all
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- provider_services: read all; write only own
drop policy if exists "provider_services_select_all" on public.provider_services;
create policy "provider_services_select_all"
on public.provider_services for select
using (true);

drop policy if exists "provider_services_write_own" on public.provider_services;
create policy "provider_services_write_own"
on public.provider_services for insert
with check (auth.uid() = provider_id);

drop policy if exists "provider_services_update_own" on public.provider_services;
create policy "provider_services_update_own"
on public.provider_services for update
using (auth.uid() = provider_id)
with check (auth.uid() = provider_id);

drop policy if exists "provider_services_delete_own" on public.provider_services;
create policy "provider_services_delete_own"
on public.provider_services for delete
using (auth.uid() = provider_id);

-- locations: read all; write only own
drop policy if exists "locations_select_all" on public.locations;
create policy "locations_select_all"
on public.locations for select
using (true);

drop policy if exists "locations_write_own" on public.locations;
create policy "locations_write_own"
on public.locations for insert
with check (auth.uid() = profile_id);

drop policy if exists "locations_update_own" on public.locations;
create policy "locations_update_own"
on public.locations for update
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

drop policy if exists "locations_delete_own" on public.locations;
create policy "locations_delete_own"
on public.locations for delete
using (auth.uid() = profile_id);

-- provider_role_requests: owner can read/insert own; admin can read all
drop policy if exists "provider_role_requests_insert_own" on public.provider_role_requests;
create policy "provider_role_requests_insert_own"
on public.provider_role_requests for insert
with check (auth.uid() = profile_id);

drop policy if exists "provider_role_requests_select_owner_or_admin" on public.provider_role_requests;
create policy "provider_role_requests_select_owner_or_admin"
on public.provider_role_requests for select
using (
  auth.uid() = profile_id
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true)
);

drop policy if exists "provider_role_requests_admin_update" on public.provider_role_requests;
create policy "provider_role_requests_admin_update"
on public.provider_role_requests for update
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- ad tables: read active ads for all; write only admin
drop policy if exists "ads_select_active" on public.ads;
create policy "ads_select_active"
on public.ads for select
using (
  is_active = true
  and (start_date is null or start_date <= current_date)
  and (end_date is null or end_date >= current_date)
);

drop policy if exists "ads_admin_write" on public.ads;
create policy "ads_admin_write"
on public.ads for all
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

drop policy if exists "ad_clients_admin_write" on public.ad_clients;
create policy "ad_clients_admin_write"
on public.ad_clients for all
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

drop policy if exists "ad_clients_select_admin" on public.ad_clients;
create policy "ad_clients_select_admin"
on public.ad_clients for select
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- ad_impressions: user can insert/select own only
drop policy if exists "ad_impressions_insert_own" on public.ad_impressions;
create policy "ad_impressions_insert_own"
on public.ad_impressions for insert
with check (auth.uid() = profile_id);

drop policy if exists "ad_impressions_select_own" on public.ad_impressions;
create policy "ad_impressions_select_own"
on public.ad_impressions for select
using (auth.uid() = profile_id);

-- jobs: customer creates own; customer/provider can read jobs they are involved in
drop policy if exists "jobs_insert_customer" on public.jobs;
create policy "jobs_insert_customer"
on public.jobs for insert
with check (auth.uid() = customer_id);

drop policy if exists "jobs_select_participants" on public.jobs;
create policy "jobs_select_participants"
on public.jobs for select
using (auth.uid() = customer_id or auth.uid() = provider_id);

drop policy if exists "jobs_update_participants" on public.jobs;
create policy "jobs_update_participants"
on public.jobs for update
using (auth.uid() = customer_id or auth.uid() = provider_id)
with check (auth.uid() = customer_id or auth.uid() = provider_id);

-- ---------------------------------------------------------------------
-- Seed categories (can be extended anytime)
-- ---------------------------------------------------------------------
insert into public.service_categories (name, icon_key, is_active)
values
  ('Electrician', 'electrician', true),
  ('Plumber', 'plumber', true),
  ('Builder', 'builder', true),
  ('Carpenter', 'carpenter', true),
  ('Painter', 'painter', true),
  ('Mechanic', 'mechanic', true),
  ('Gardener', 'gardener', true)
on conflict (name) do update
set icon_key = excluded.icon_key,
    is_active = excluded.is_active,
    updated_at = now();

commit;

